#!/usr/bin/env zsh

dotfiles_dir="dotfiles"
script_dir="$(cd "$(dirname "$0")" && pwd)"

cd "$script_dir/$dotfiles_dir"

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="wezterm,zsh,starship,tmux"
fi

for folder in ${(s:,:)STOW_FOLDERS}
do
    #stow -D --target "$XDG_CONFIG_HOME" "$folder"
    #stow --target "$XDG_CONFIG_HOME" "$folder"
    if stow -n -D --target "$HOME" "$folder" >/dev/null 2>&1; then
        echo "Unstowing $folder"
	stow -D --target "$HOME" "$folder"
    else
        echo "$folder is not stowed, nothing to unstow"
    fi
    if [[ "$1" != "rm" ]] then
        echo "Stowing "$folder" content to $HOME"
        stow --target "$HOME" "$folder"
    fi
done
