#!/usr/bin/env zsh
# set -x
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir"

stow_ignore="$script_dir/.stow-local-ignore"
stow_target="$XDG_CONFIG_HOME"
stow_dir="."

echo "Unstowing everyting/doing cleanup"
stow -D --ignore "$stow_ignore" --target "$stow_target" "$stow_dir"

zshrc_path="$HOME/.zshrc"
zsh_profile_source_line="source $XDG_CONFIG_HOME/zsh/.zsh_profile"

echo "Cleaning up zshrc"
sed -i "\|^$zsh_profile_source_line\$|d" $zshrc_path

if [[ "$1" != "rm" ]]; then
    echo "Stowing content to $XDG_CONFIG_HOME"
    stow --ignore "$stow_ignore" --target "$stow_target" "$stow_dir"

    echo "Linking root zshrc to custom profile"
    if [ ! -f "$zshrc_path" ]; then
        touch "$zshrc_path"
    fi

    if ! grep -qF "$zsh_profile_source_line" "$zshrc_path"; then
        echo "$zsh_profile_source_line" >> "$zshrc_path"
    fi
fi

source "$zshrc_path"
echo "Zshrc updated and sourced!"

if [[ "$1" != "rm" ]]; then
    if command -v brew &> /dev/null; then
        echo "Syncing and updating homebrew"
        brew bundle --file "$script_dir/homebrew/Brewfile"
        # xargs brew install < "$script_dir/homebrew/leaves.txt"
        # brew update
    else
        echo "Homebrew not installed, please install it and sync the dependencies manually"
    fi
fi
