return {
  "mason-org/mason-lspconfig.nvim",
  dependencies = {
    { "mason-org/mason.nvim", opts = {} },
    {
      "WhoIsSethDaniel/mason-tool-installer.nvim",
      opts = { ensure_installed = { "prettierd", "eslint_d", "stylua" } },
    },
  },
  opts = {
    ensure_installed = {
      "angularls",
      "ansiblels",
      "bashls",
      "buf_ls",
      "css_variables",
      "cssls",
      "docker_compose_language_service",
      "dockerls",
      "emmet_ls",
      "gh_actions_ls",
      "graphql",
      "helm_ls",
      "html",
      "jsonls",
      "just",
      "lua_ls",
      "postgres_lsp",
      "tailwindcss",
      "terraformls",
      "ts_ls",
      "yamlls",
    },
  },
}
